import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { dark } from '@clerk/themes';
import { ThemeProvider } from 'next-themes';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
      <body className={inter.className}>
        
        <ThemeProvider 
        attribute="class"
        forcedTheme='dark'
        storageKey='stream-app-theme'
        >
        <Toaster/>
          {children}
        </ThemeProvider>
      </body>
      </html>
    </ClerkProvider>
    
  );
}
